version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: postgresql
    environment:
      POSTGRES_USER: ecomunidad
      POSTGRES_PASSWORD: xBGTGHfX5Pss2jqGYFV1yfFqeFEBdwWw
      POSTGRES_DB: ecotrackdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ecomunidad@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin2024
    ports:
      - "8080:80"
    depends_on:
      - postgres

volumes:
  postgres_data:


